C={0: 'Adam Levine',
 1: 'Ajay Devgan',
 2: 'Ariana Grande',
 3: 'Chris Hemsworth',
 4: 'Dipika Padukone',
 5: "Genelia D'Souza",
 6: 'RAnbir singh',
 7: 'aamir khan',
 8: 'alina tal',
 9: 'anushka shetty',
 10: 'arya',
 11: 'belrim destani',
 12: 'bradely james',
 13: 'brice davidson',
 14: 'govinda',
 15: 'himesh reshamiya',
 16: 'hina khan',
 17: 'jessica Lucas',
 18: 'josh brolin',
 19: 'karina gonzalez',
 20: 'kylie jenner',
 21: 'matthew davis',
 22: 'nandish',
 23: 'neha dhupia',
 24: 'om puri',
 25: 'ranbir kapoor',
 26: 'sanjay dutt',
 27: 'sarah shahi',
 28: 'sidharth malhotra',
 29: 'sonakshi sinha',
 30: 'surveeen chawla',
 31: 'varun dhavan'}
